# Generated by Django 3.2.6 on 2021-08-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('userID', models.CharField(max_length=200)),
                ('roomID', models.CharField(max_length=200)),
            ],
        ),
    ]
